# Generated by Django 4.0.2 on 2025-06-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_player_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.CharField(max_length=255, verbose_name='Describe yourself'),
        ),
    ]
